SET(USE_CLANG   TRUE Cached internal "")

SET(DEBUG_BUILD True CACHE INTERNAL "")
SET(USE_HW_FPU  TRUE CACHE INTERNAL "")
SET(USE_CH32v3x_HW_IRQ_STACK TRUE CACHE INTERNAL "")
#SET(USE_CH32v3x_PURE_RAM TRUE CACHE INTERNAL "")
SET(LN_LTO "-flto"  CACHE INTERNAL "")
